version: "3.8"
services:
  homeassistant:
    restart: unless-stopped
    network_mode: host
    privileged: true
    ports: []
    volumes:
      - ./volume/config:/config
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    networks: []
    depends_on: []
    image: linuxserver/homeassistant:2023.11.2
networks: {}
